### ISSUE TITLE
Scala 3 support 

### ISSUE THREAD

**Issue by exoego** [ThoughtWorksInc/enableIf.scala#56]
Unfortunately Scala 3 does not support macro annotation and seems no plan.
Do you plan something to support Scala 3?

I am wondering that compiler plugin can be alternative
https://github.com/liufengyun/scala3-plugin-example

**Comment by Atry** [comment]
Scala compiler plugin runs after type checking, therefore it cannot be used as an alternative to macro annotation.

**Comment by exoego** [comment]
Hmm, that is sorry 😅 
I will try to find other approach on my project.
Thanks!
