### ISSUE TITLE
Enhanced enableIf for arbitrary jar dependencies

### ISSUE THREAD

**Issue by da-liii** [ThoughtWorksInc/enableIf.scala#57]
``` scala
  @enableIf(c =>
    c.classPath.exists(
      _.getPath.matches(".*spark-catalyst_2\\.\\d+-3\\.2\\..*")
    )
  )
```

@Renkai is using enableIf to conditional compile a Spark-based project here: https://github.com/eto-ai/rikai/pull/531

Using classpath and regex, it works fine. It would be nice to have a special macro like `enableClasspath`.

**Comment by da-liii** [comment]
I'd like to have:

``` scala
enableWithClasspath(regex: String)
enableWithClasspath(artifactId: String, versionRegex: String)
```

**Comment by Atry** [comment]
I think `c.classPath.exists` is good.

**Comment by da-liii** [comment]
Working on a pull request now.
